spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/simpleblog
    driver-class-name: org.mariadb.jdbc.Driver
    password: '0000'
    username: bloguser
  jpa:
    hibernate:
      ddl-auto: update

login:
  url: /chat-blog/login

front:
  url: ??

security:
  token:
    access:
      expirationMinutes: 60
    refresh:
      expirationDays: 1
