spring:
  profiles:
    active: database

login:
  url: /chat-blog/public/login

logout:
  url: /chat-blog/user/logout

front:
  url: ??

server:
  servlet:
    session:
      cookie:
        http-only: true

security:
  token:
    access:
      expirationMinutes: 15
    refresh:
      expirationDays: 1
