PATCH http://localhost:8080/chat-blog/user/member/changed/pwd
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImFkZHJlc3MiOiJoZWxsb0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzE1MzMwMDc0LCJleHAiOjE3MTUzMzM2NzR9.1GyFW8aOvzs0_X_igbY2sbeQhIIqzLXnRhKG-F2SDVw

{
  "beforePassword" : "@1213eee",
  "afterPassword" : "a12345678@"
}