POST http://localhost:8080/chat-blog/user/logout
access: eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImFkZHJlc3MiOiJoZWxsb0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzE1MzM2MTYxLCJleHAiOjE3MTUzMzk3NjF9.1mtiGzGMUbPLHs3R15O3wlwhdzg6T4nXHpKdn37f7jg
Cookie: refresh=eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6InJlZnJlc2giLCJhZGRyZXNzIjoiaGVsbG9AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTcxNTMzNjE2MSwiZXhwIjoxNzE1NDIyNTYxfQ.MrO8HrEAv6ALwyvUvLVHVrWV_5OD6LNaPRHI4j1r8nM