GET localhost:8080/chat-blog/
access: eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImFkZHJlc3MiOiJoZWxsb0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzE0NDYwODc2LCJleHAiOjE3MTQ0NjQ0NzZ9.-1U0Sej8pTKrvuvem7X-K6Tuo6BotJoHsoc6IX9LkRg